# Generated by Django 3.2.8 on 2022-02-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='for_today',
            field=models.BooleanField(default=False),
        ),
    ]
